### ISSUE TITLE
rerun l2 processing

### ISSUE THREAD

**Issue by BengtRydberg** [Odin-SMR/odin-api#101]
reurn l2 processing for january and december

There was an an error in apriori data for these months.

When this is done make sure the level2 netcdf files are updated.

**Comment by BengtRydberg** [comment]
@donal-mur Can you describe what FMs we should re-run.

**Comment by donal-mur** [comment]
At least FM2 should be rerun.  That is the mode that shows the most effect 
I have not identified Other FMs specifically but we suspect all strong lines should be affected. Ie. the water modes 13 and 19 but they may have had their own a-priori ??
