### ISSUE TITLE
Acknowledgement to SNIC

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin-api#109]
Vi måste skicka en rapport på projektet och noterade att vi bör ha en acknowledgement till SNIC i publikationer och lika bra att ha den på websidan också

> The computations/data handling/[SIMILAR] were/was enabled by resources provided by the Swedish National Infrastructure for Computing (SNIC) at [SNIC CENTRE] partially funded by the Swedish Research Council through grant agreement no. 2018-05973.

**Comment by skymandr** [comment]
@donal-mur Where on the homepage should this go?

**Comment by donal-mur** [comment]
How about in this blick
The consortium bringing data from space all the way to you


On 1 Apr 2021, at 11:46, Andreas Skyman ***@***.******@***.***>> wrote:



@donal-mur<https://github.com/donal-mur> Where on the homepage should this go?
