### ISSUE TITLE
Posting results to level2 api fails

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#32]
A worker image cannot post the result to l2-api.

Give it a try to solve it with pycryptodome otherwise revert crypto.

**Comment by BengtRydberg** [comment]
ser ut att vara ett "enkelt" problem. när jag går in i imagen som körs och startar python
och försöker få tag i våran secret key så är den tom

>>> SECRET_KEY = os.environ.get(
...     'SECRET_KEY', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
... )
>>> SECRET_KEY
''
när jag testar att använda den korrekta nyckeln (i körande imagen) och försöker avkoda ett meddelande som jag skapat lokalt i ett qqjobs virtualenv får jag rätt avkodning.

**Comment by joakimmoller** [comment]
close?

**Comment by BengtRydberg** [comment]
ska vi deploya och se att det funkar i praktiken först? eller ska vi vara nöjda att det snurrar på?
