### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#34]
Odin-SMR repositories lack LICENSE files. In principle, though it is not generally enforced, repositories on GitHub should have an explicit free license to count as open source repositories. MIT should be fine for everything except maybe docs (MIT might work here, otherwise CC:By-SA, CC:By or possibly GFDL should be compatible with Chalmers' library Open Access policy, if I recall correctly).

**Comment by joakimmoller** [comment]
@donal-mur please choose.

**Comment by donal-mur** [comment]
@joakimmoller Ole Martin är mycket bättre på detta än jag. MIT låter fin för min del 
Donal
