### ISSUE TITLE
Finish the recommended products table

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin-api#37]
The recommendations table on https://odin.rss.chalmers.se/dataaccess is incomplete. It should be fleshed out with more recommendations, once @donal-mur has had a chance to compile them.

**Comment by skymandr** [comment]
Gabriele asked about this, see #71

**Comment by donal-mur** [comment]
take this from the new PVER?

**Comment by skymandr** [comment]
Perhaps add a link to PVER next to the table as well then: "For more details, see ... "
