### ISSUE TITLE
Migrate docker images

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#41]
Move all images from Molflow's private docker repositories to OdinSMR public repository

**Comment by skymandr** [comment]
Which ones remain?

**Comment by joakimmoller** [comment]
I believe finding out which ones is with in the task :)

**Comment by skymandr** [comment]
I suspect one of them is hermod...

**Comment by skymandr** [comment]
https://github.com/search?q=org%3AOdin-SMR+docker2.molflow.com&type=Code
