### ISSUE TITLE
Knäpp Apriori, slutet år 2007?

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#43]
Det visade sig att kanske 10% av resultaten har 10 gånger så höga ozon som det bör vara. Ett exempel är scan number 3456049433

review av odin-api. Kontrollera om det är något fel?.

**Comment by local-minimum** [comment]
Detta är inte helt skottårssäkert väl?
```
def get_vmr_interpolated_for_doy(vmr, doys, doy):
    deltas = np.min(
        [
            (doys[:, 0].astype(float) - doy) % 365,
            (doy - doys[:, 0].astype(float)) % 365,
        ],
        axis=0,
    )
    ind1, ind2 = np.arange(deltas.size)[np.argsort(deltas)][:2]
    doy1 = float(doys[ind1].item())
    doy2 = float(doys[ind2].item())
    ddoy = min((doy1 - doy2) % 365, (doy2 - doy1) % 365)
    w1 = deltas[ind2] / ddoy
    w2 = deltas[ind1] / ddoy
    vmr = vmr[:, :, :, ind1] * w1 + vmr[:, :, :, ind2] * w2
    return vmr[:, :, 0]
```

**Comment by local-minimum** [comment]
Det finns en hel del info på #44

**Comment by local-minimum** [comment]
Jag kikade lite på detta igen, i själva utläsningen från level2 databasen tycker jag det ser ut som om innehållet bara direkt skickas vidare till klienten utan processning. Dvs om det är fel i dessa scans är det fel på processningen.

Det ser inte heller ut som att data manipuleras på något relevant sätt när level2 resultat postas.

Så jag antar att frågan enbart rör enpointen där man får ut apriori...

Förutom det marginella felet i viktningen m.a.p. day of year interpoleringen vid skottår för datum mellan årets sista apriori och första apriori så ser jag inte någonting underligt alls i hur datan levereras.

Om jag plottar upp allt i `/data/apriori/apriori_O3.mat` (antar att den version som finns här i repot är samma som används i produktion) som en heatmap så ser jag inga oväntade artifakter eller att det skulle vara några markanta avvikelser m.a.p. på tryck / dag på året eller latitud.

Det enda jag ser som kan påverka värdet med kring en faktor tio är trycket. Är det möjligt att trycket är fel snarare än O3? Jag vet inte alls hur tryck kommer in här, men som jag förstår det så finns det apriori för 721 olika tryck för varje (dag, latitud, altitud) kombination.

**Comment by local-minimum** [comment]
@donal-mur, hur och vem går vidare med detta?

**Comment by donal-mur** [comment]
Du kan prova med mig.  Jag kan tro att problemet ligger i a-priori funktionen , Bengt har fixat i den förut så han kan också vara bra .

Donal

---------------------------------------------------------------
Donal Murtagh
Prof Global Environmental Measurements
Chalmers tekniska högskola
tel +46 31 772 56 51
donal.murtagh@chalmers.se<mailto:donal.murtagh@chalmers.se>



On 10 Aug 2020, at 11:15, Martin Zackrisson <notifications@github.com<mailto:notifications@github.com>> wrote:



@donal-mur<https://github.com/donal-mur>, hur och vem går vidare med detta?

**Comment by donal-mur** [comment]
Ok I have found something weird in the function -  under certain conditions the weights w1 san w2 do not sum to 1.  With my test numbers it might make a 20% diff in the apron but with the real numbers it may well be a faktor 10 
 
The script's logic is unnecessarily   complex I hardly understand how it does what it does
Effectively we should just find where the DOY  fits in the DOYS and do a weighted average.  Only the first x days of January and last y days of dec need to be treated specially.
I made a quick mod of the script, provided what I think the doys may be the 15 of each month probably here approximated by every 15 days. and then look at the indexes and the weight for all doy. 

As you can see. the indexes are probably not correct and for some days the sum of the weights is greater than 1 which will give rubbish



#def get_vmr_interpolated_for_doy(vmr, doys, doy):
def test(doy):
    doys=np.array(range(15,365,30),ndmin=2).T
    #doy=361
    deltas = np.min(
        [
            (doys[:, 0].astype(float) - doy) % 365,
            (doy - doys[:, 0].astype(float)) % 365,
        ],
        axis=0,
    )
    ind1, ind2 = np.arange(deltas.size)[np.argsort(deltas)][:2]
    doy1 = float(doys[ind1].item())
    doy2 = float(doys[ind2].item())
    ddoy = min((doy1 - doy2) % 365, (doy2 - doy1) % 365)
    w1 = deltas[ind2] / ddoy
    w2 = deltas[ind1] / ddoy
    return (ind1,ind2,w1,w2)
#    vmr = vmr[:, :, :, ind1] * w1 + vmr[:, :, :, ind2] * w2
#    return vmr[:, :, 0]

for i in range(1,366):
    id1,id2,w1,w2=test(i)
    print (i,id1,id2,w1,w2, w1+w2)

1 0 11 0.6 0.4 1.0
2 0 11 0.6285714285714286 0.37142857142857144 1.0
3 0 11 0.6571428571428571 0.34285714285714286 1.0
4 0 11 0.6857142857142857 0.3142857142857143 1.0
5 0 11 0.7142857142857143 0.2857142857142857 1.0
6 0 11 0.7428571428571429 0.2571428571428571 1.0
7 0 11 0.7714285714285715 0.22857142857142856 1.0
8 0 11 0.8 0.2 1.0
9 0 11 0.8285714285714286 0.17142857142857143 1.0
10 0 11 0.8571428571428571 0.14285714285714285 1.0
11 0 11 0.8857142857142857 0.11428571428571428 1.0
12 0 11 0.9142857142857143 0.08571428571428572 1.0
13 0 1 1.0666666666666667 0.06666666666666667 1.1333333333333333
14 0 1 1.0333333333333334 0.03333333333333333 1.0666666666666669
15 0 1 1.0 0.0 1.0
16 0 1 0.9666666666666667 0.03333333333333333 1.0
17 0 1 0.9333333333333333 0.06666666666666667 1.0
18 0 1 0.9 0.1 1.0
19 0 1 0.8666666666666667 0.13333333333333333 1.0
20 0 1 0.8333333333333334 0.16666666666666666 1.0
21 0 1 0.8 0.2 1.0
22 0 1 0.7666666666666667 0.23333333333333334 1.0
23 0 1 0.7333333333333333 0.26666666666666666 1.0
24 0 1 0.7 0.3 1.0
25 0 1 0.6666666666666666 0.3333333333333333 1.0
26 0 1 0.6333333333333333 0.36666666666666664 1.0
27 0 1 0.6 0.4 1.0
28 0 1 0.5666666666666667 0.43333333333333335 1.0
29 0 1 0.5333333333333333 0.4666666666666667 1.0
30 0 1 0.5 0.5 1.0
31 1 0 0.5333333333333333 0.4666666666666667 1.0
32 1 0 0.5666666666666667 0.43333333333333335 1.0
33 1 0 0.6 0.4 1.0
34 1 0 0.6333333333333333 0.36666666666666664 1.0
35 1 0 0.6666666666666666 0.3333333333333333 1.0
36 1 0 0.7 0.3 1.0
37 1 0 0.7333333333333333 0.26666666666666666 1.0
38 1 0 0.7666666666666667 0.23333333333333334 1.0
39 1 0 0.8 0.2 1.0
40 1 0 0.8333333333333334 0.16666666666666666 1.0
41 1 0 0.8666666666666667 0.13333333333333333 1.0
42 1 0 0.9 0.1 1.0
43 1 0 0.9333333333333333 0.06666666666666667 1.0
44 1 0 0.9666666666666667 0.03333333333333333 1.0
45 1 0 1.0 0.0 1.0
46 1 2 0.9666666666666667 0.03333333333333333 1.0
47 1 2 0.9333333333333333 0.06666666666666667 1.0
48 1 2 0.9 0.1 1.0
49 1 2 0.8666666666666667 0.13333333333333333 1.0
50 1 2 0.8333333333333334 0.16666666666666666 1.0
51 1 2 0.8 0.2 1.0
52 1 2 0.7666666666666667 0.23333333333333334 1.0
53 1 2 0.7333333333333333 0.26666666666666666 1.0
54 1 2 0.7 0.3 1.0
55 1 2 0.6666666666666666 0.3333333333333333 1.0
56 1 2 0.6333333333333333 0.36666666666666664 1.0
57 1 2 0.6 0.4 1.0
58 1 2 0.5666666666666667 0.43333333333333335 1.0
59 1 2 0.5333333333333333 0.4666666666666667 1.0
60 1 2 0.5 0.5 1.0
61 2 1 0.5333333333333333 0.4666666666666667 1.0
62 2 1 0.5666666666666667 0.43333333333333335 1.0
63 2 1 0.6 0.4 1.0
64 2 1 0.6333333333333333 0.36666666666666664 1.0
65 2 1 0.6666666666666666 0.3333333333333333 1.0
66 2 1 0.7 0.3 1.0
67 2 1 0.7333333333333333 0.26666666666666666 1.0
68 2 1 0.7666666666666667 0.23333333333333334 1.0
69 2 1 0.8 0.2 1.0
70 2 1 0.8333333333333334 0.16666666666666666 1.0
71 2 1 0.8666666666666667 0.13333333333333333 1.0
72 2 1 0.9 0.1 1.0
73 2 1 0.9333333333333333 0.06666666666666667 1.0
74 2 1 0.9666666666666667 0.03333333333333333 1.0
75 2 1 1.0 0.0 1.0
76 2 3 0.9666666666666667 0.03333333333333333 1.0
77 2 3 0.9333333333333333 0.06666666666666667 1.0
78 2 3 0.9 0.1 1.0
79 2 3 0.8666666666666667 0.13333333333333333 1.0
80 2 3 0.8333333333333334 0.16666666666666666 1.0
81 2 3 0.8 0.2 1.0
82 2 3 0.7666666666666667 0.23333333333333334 1.0
83 2 3 0.7333333333333333 0.26666666666666666 1.0
84 2 3 0.7 0.3 1.0
85 2 3 0.6666666666666666 0.3333333333333333 1.0
86 2 3 0.6333333333333333 0.36666666666666664 1.0
87 2 3 0.6 0.4 1.0
88 2 3 0.5666666666666667 0.43333333333333335 1.0
89 2 3 0.5333333333333333 0.4666666666666667 1.0
90 2 3 0.5 0.5 1.0
91 3 2 0.5333333333333333 0.4666666666666667 1.0
92 3 2 0.5666666666666667 0.43333333333333335 1.0
93 3 2 0.6 0.4 1.0
94 3 2 0.6333333333333333 0.36666666666666664 1.0
95 3 2 0.6666666666666666 0.3333333333333333 1.0
96 3 2 0.7 0.3 1.0
97 3 2 0.7333333333333333 0.26666666666666666 1.0
98 3 2 0.7666666666666667 0.23333333333333334 1.0
99 3 2 0.8 0.2 1.0
100 3 2 0.8333333333333334 0.16666666666666666 1.0
101 3 2 0.8666666666666667 0.13333333333333333 1.0
102 3 2 0.9 0.1 1.0
103 3 2 0.9333333333333333 0.06666666666666667 1.0
104 3 2 0.9666666666666667 0.03333333333333333 1.0
105 3 2 1.0 0.0 1.0
106 3 4 0.9666666666666667 0.03333333333333333 1.0
107 3 4 0.9333333333333333 0.06666666666666667 1.0
108 3 4 0.9 0.1 1.0
109 3 4 0.8666666666666667 0.13333333333333333 1.0
110 3 4 0.8333333333333334 0.16666666666666666 1.0
111 3 4 0.8 0.2 1.0
112 3 4 0.7666666666666667 0.23333333333333334 1.0
113 3 4 0.7333333333333333 0.26666666666666666 1.0
114 3 4 0.7 0.3 1.0
115 3 4 0.6666666666666666 0.3333333333333333 1.0
116 3 4 0.6333333333333333 0.36666666666666664 1.0
117 3 4 0.6 0.4 1.0
118 3 4 0.5666666666666667 0.43333333333333335 1.0
119 3 4 0.5333333333333333 0.4666666666666667 1.0
120 3 4 0.5 0.5 1.0
121 4 3 0.5333333333333333 0.4666666666666667 1.0
122 4 3 0.5666666666666667 0.43333333333333335 1.0
123 4 3 0.6 0.4 1.0
124 4 3 0.6333333333333333 0.36666666666666664 1.0
125 4 3 0.6666666666666666 0.3333333333333333 1.0
126 4 3 0.7 0.3 1.0
127 4 3 0.7333333333333333 0.26666666666666666 1.0
128 4 3 0.7666666666666667 0.23333333333333334 1.0
129 4 3 0.8 0.2 1.0
130 4 3 0.8333333333333334 0.16666666666666666 1.0
131 4 3 0.8666666666666667 0.13333333333333333 1.0
132 4 3 0.9 0.1 1.0
133 4 3 0.9333333333333333 0.06666666666666667 1.0
134 4 3 0.9666666666666667 0.03333333333333333 1.0
135 4 3 1.0 0.0 1.0
136 4 5 0.9666666666666667 0.03333333333333333 1.0
137 4 5 0.9333333333333333 0.06666666666666667 1.0
138 4 5 0.9 0.1 1.0
139 4 5 0.8666666666666667 0.13333333333333333 1.0
140 4 5 0.8333333333333334 0.16666666666666666 1.0
141 4 5 0.8 0.2 1.0
142 4 5 0.7666666666666667 0.23333333333333334 1.0
143 4 5 0.7333333333333333 0.26666666666666666 1.0
144 4 5 0.7 0.3 1.0
145 4 5 0.6666666666666666 0.3333333333333333 1.0
146 4 5 0.6333333333333333 0.36666666666666664 1.0
147 4 5 0.6 0.4 1.0
148 4 5 0.5666666666666667 0.43333333333333335 1.0
149 4 5 0.5333333333333333 0.4666666666666667 1.0
150 4 5 0.5 0.5 1.0
151 5 4 0.5333333333333333 0.4666666666666667 1.0
152 5 4 0.5666666666666667 0.43333333333333335 1.0
153 5 4 0.6 0.4 1.0
154 5 4 0.6333333333333333 0.36666666666666664 1.0
155 5 4 0.6666666666666666 0.3333333333333333 1.0
156 5 4 0.7 0.3 1.0
157 5 4 0.7333333333333333 0.26666666666666666 1.0
158 5 4 0.7666666666666667 0.23333333333333334 1.0
159 5 4 0.8 0.2 1.0
160 5 4 0.8333333333333334 0.16666666666666666 1.0
161 5 4 0.8666666666666667 0.13333333333333333 1.0
162 5 4 0.9 0.1 1.0
163 5 4 0.9333333333333333 0.06666666666666667 1.0
164 5 4 0.9666666666666667 0.03333333333333333 1.0
165 5 4 1.0 0.0 1.0
166 5 6 0.9666666666666667 0.03333333333333333 1.0
167 5 6 0.9333333333333333 0.06666666666666667 1.0
168 5 6 0.9 0.1 1.0
169 5 6 0.8666666666666667 0.13333333333333333 1.0
170 5 6 0.8333333333333334 0.16666666666666666 1.0
171 5 6 0.8 0.2 1.0
172 5 6 0.7666666666666667 0.23333333333333334 1.0
173 5 6 0.7333333333333333 0.26666666666666666 1.0
174 5 6 0.7 0.3 1.0
175 5 6 0.6666666666666666 0.3333333333333333 1.0
176 5 6 0.6333333333333333 0.36666666666666664 1.0
177 5 6 0.6 0.4 1.0
178 5 6 0.5666666666666667 0.43333333333333335 1.0
179 5 6 0.5333333333333333 0.4666666666666667 1.0
180 5 6 0.5 0.5 1.0
181 6 5 0.5333333333333333 0.4666666666666667 1.0
182 6 5 0.5666666666666667 0.43333333333333335 1.0
183 6 5 0.6 0.4 1.0
184 6 5 0.6333333333333333 0.36666666666666664 1.0
185 6 5 0.6666666666666666 0.3333333333333333 1.0
186 6 5 0.7 0.3 1.0
187 6 5 0.7333333333333333 0.26666666666666666 1.0
188 6 5 0.7666666666666667 0.23333333333333334 1.0
189 6 5 0.8 0.2 1.0
190 6 5 0.8333333333333334 0.16666666666666666 1.0
191 6 5 0.8666666666666667 0.13333333333333333 1.0
192 6 5 0.9 0.1 1.0
193 6 5 0.9333333333333333 0.06666666666666667 1.0
194 6 5 0.9666666666666667 0.03333333333333333 1.0
195 6 5 1.0 0.0 1.0
196 6 7 0.9666666666666667 0.03333333333333333 1.0
197 6 7 0.9333333333333333 0.06666666666666667 1.0
198 6 7 0.9 0.1 1.0
199 6 7 0.8666666666666667 0.13333333333333333 1.0
200 6 7 0.8333333333333334 0.16666666666666666 1.0
201 6 7 0.8 0.2 1.0
202 6 7 0.7666666666666667 0.23333333333333334 1.0
203 6 7 0.7333333333333333 0.26666666666666666 1.0
204 6 7 0.7 0.3 1.0
205 6 7 0.6666666666666666 0.3333333333333333 1.0
206 6 7 0.6333333333333333 0.36666666666666664 1.0
207 6 7 0.6 0.4 1.0
208 6 7 0.5666666666666667 0.43333333333333335 1.0
209 6 7 0.5333333333333333 0.4666666666666667 1.0
210 6 7 0.5 0.5 1.0
211 7 6 0.5333333333333333 0.4666666666666667 1.0
212 7 6 0.5666666666666667 0.43333333333333335 1.0
213 7 6 0.6 0.4 1.0
214 7 6 0.6333333333333333 0.36666666666666664 1.0
215 7 6 0.6666666666666666 0.3333333333333333 1.0
216 7 6 0.7 0.3 1.0
217 7 6 0.7333333333333333 0.26666666666666666 1.0
218 7 6 0.7666666666666667 0.23333333333333334 1.0
219 7 6 0.8 0.2 1.0
220 7 6 0.8333333333333334 0.16666666666666666 1.0
221 7 6 0.8666666666666667 0.13333333333333333 1.0
222 7 6 0.9 0.1 1.0
223 7 6 0.9333333333333333 0.06666666666666667 1.0
224 7 6 0.9666666666666667 0.03333333333333333 1.0
225 7 6 1.0 0.0 1.0
226 7 8 0.9666666666666667 0.03333333333333333 1.0
227 7 8 0.9333333333333333 0.06666666666666667 1.0
228 7 8 0.9 0.1 1.0
229 7 8 0.8666666666666667 0.13333333333333333 1.0
230 7 8 0.8333333333333334 0.16666666666666666 1.0
231 7 8 0.8 0.2 1.0
232 7 8 0.7666666666666667 0.23333333333333334 1.0
233 7 8 0.7333333333333333 0.26666666666666666 1.0
234 7 8 0.7 0.3 1.0
235 7 8 0.6666666666666666 0.3333333333333333 1.0
236 7 8 0.6333333333333333 0.36666666666666664 1.0
237 7 8 0.6 0.4 1.0
238 7 8 0.5666666666666667 0.43333333333333335 1.0
239 7 8 0.5333333333333333 0.4666666666666667 1.0
240 7 8 0.5 0.5 1.0
241 8 7 0.5333333333333333 0.4666666666666667 1.0
242 8 7 0.5666666666666667 0.43333333333333335 1.0
243 8 7 0.6 0.4 1.0
244 8 7 0.6333333333333333 0.36666666666666664 1.0
245 8 7 0.6666666666666666 0.3333333333333333 1.0
246 8 7 0.7 0.3 1.0
247 8 7 0.7333333333333333 0.26666666666666666 1.0
248 8 7 0.7666666666666667 0.23333333333333334 1.0
249 8 7 0.8 0.2 1.0
250 8 7 0.8333333333333334 0.16666666666666666 1.0
251 8 7 0.8666666666666667 0.13333333333333333 1.0
252 8 7 0.9 0.1 1.0
253 8 7 0.9333333333333333 0.06666666666666667 1.0
254 8 7 0.9666666666666667 0.03333333333333333 1.0
255 8 7 1.0 0.0 1.0
256 8 9 0.9666666666666667 0.03333333333333333 1.0
257 8 9 0.9333333333333333 0.06666666666666667 1.0
258 8 9 0.9 0.1 1.0
259 8 9 0.8666666666666667 0.13333333333333333 1.0
260 8 9 0.8333333333333334 0.16666666666666666 1.0
261 8 9 0.8 0.2 1.0
262 8 9 0.7666666666666667 0.23333333333333334 1.0
263 8 9 0.7333333333333333 0.26666666666666666 1.0
264 8 9 0.7 0.3 1.0
265 8 9 0.6666666666666666 0.3333333333333333 1.0
266 8 9 0.6333333333333333 0.36666666666666664 1.0
267 8 9 0.6 0.4 1.0
268 8 9 0.5666666666666667 0.43333333333333335 1.0
269 8 9 0.5333333333333333 0.4666666666666667 1.0
270 8 9 0.5 0.5 1.0
271 9 8 0.5333333333333333 0.4666666666666667 1.0
272 9 8 0.5666666666666667 0.43333333333333335 1.0
273 9 8 0.6 0.4 1.0
274 9 8 0.6333333333333333 0.36666666666666664 1.0
275 9 8 0.6666666666666666 0.3333333333333333 1.0
276 9 8 0.7 0.3 1.0
277 9 8 0.7333333333333333 0.26666666666666666 1.0
278 9 8 0.7666666666666667 0.23333333333333334 1.0
279 9 8 0.8 0.2 1.0
280 9 8 0.8333333333333334 0.16666666666666666 1.0
281 9 8 0.8666666666666667 0.13333333333333333 1.0
282 9 8 0.9 0.1 1.0
283 9 8 0.9333333333333333 0.06666666666666667 1.0
284 9 8 0.9666666666666667 0.03333333333333333 1.0
285 9 8 1.0 0.0 1.0
286 9 10 0.9666666666666667 0.03333333333333333 1.0
287 9 10 0.9333333333333333 0.06666666666666667 1.0
288 9 10 0.9 0.1 1.0
289 9 10 0.8666666666666667 0.13333333333333333 1.0
290 9 10 0.8333333333333334 0.16666666666666666 1.0
291 9 10 0.8 0.2 1.0
292 9 10 0.7666666666666667 0.23333333333333334 1.0
293 9 10 0.7333333333333333 0.26666666666666666 1.0
294 9 10 0.7 0.3 1.0
295 9 10 0.6666666666666666 0.3333333333333333 1.0
296 9 10 0.6333333333333333 0.36666666666666664 1.0
297 9 10 0.6 0.4 1.0
298 9 10 0.5666666666666667 0.43333333333333335 1.0
299 9 10 0.5333333333333333 0.4666666666666667 1.0
300 9 10 0.5 0.5 1.0
301 10 9 0.5333333333333333 0.4666666666666667 1.0
302 10 9 0.5666666666666667 0.43333333333333335 1.0
303 10 9 0.6 0.4 1.0
304 10 9 0.6333333333333333 0.36666666666666664 1.0
305 10 9 0.6666666666666666 0.3333333333333333 1.0
306 10 9 0.7 0.3 1.0
307 10 9 0.7333333333333333 0.26666666666666666 1.0
308 10 9 0.7666666666666667 0.23333333333333334 1.0
309 10 9 0.8 0.2 1.0
310 10 9 0.8333333333333334 0.16666666666666666 1.0
311 10 9 0.8666666666666667 0.13333333333333333 1.0
312 10 9 0.9 0.1 1.0
313 10 9 0.9333333333333333 0.06666666666666667 1.0
314 10 9 0.9666666666666667 0.03333333333333333 1.0
315 10 9 1.0 0.0 1.0
316 10 11 0.9666666666666667 0.03333333333333333 1.0
317 10 11 0.9333333333333333 0.06666666666666667 1.0
318 10 11 0.9 0.1 1.0
319 10 11 0.8666666666666667 0.13333333333333333 1.0
320 10 11 0.8333333333333334 0.16666666666666666 1.0
321 10 11 0.8 0.2 1.0
322 10 11 0.7666666666666667 0.23333333333333334 1.0
323 10 11 0.7333333333333333 0.26666666666666666 1.0
324 10 11 0.7 0.3 1.0
325 10 11 0.6666666666666666 0.3333333333333333 1.0
326 10 11 0.6333333333333333 0.36666666666666664 1.0
327 10 11 0.6 0.4 1.0
328 10 11 0.5666666666666667 0.43333333333333335 1.0
329 10 11 0.5333333333333333 0.4666666666666667 1.0
330 10 11 0.5 0.5 1.0
331 11 10 0.5333333333333333 0.4666666666666667 1.0
332 11 10 0.5666666666666667 0.43333333333333335 1.0
333 11 10 0.6 0.4 1.0
334 11 10 0.6333333333333333 0.36666666666666664 1.0
335 11 10 0.6666666666666666 0.3333333333333333 1.0
336 11 10 0.7 0.3 1.0
337 11 10 0.7333333333333333 0.26666666666666666 1.0
338 11 10 0.7666666666666667 0.23333333333333334 1.0
339 11 10 0.8 0.2 1.0
340 11 10 0.8333333333333334 0.16666666666666666 1.0
341 11 10 0.8666666666666667 0.13333333333333333 1.0
342 11 10 0.9 0.1 1.0
343 11 10 0.9333333333333333 0.06666666666666667 1.0
344 11 10 0.9666666666666667 0.03333333333333333 1.0
345 11 10 1.0 0.0 1.0
346 11 10 1.0333333333333334 0.03333333333333333 1.0666666666666669
347 11 10 1.0666666666666667 0.06666666666666667 1.1333333333333333
348 11 0 0.9142857142857143 0.08571428571428572 1.0
349 11 0 0.8857142857142857 0.11428571428571428 1.0
350 11 0 0.8571428571428571 0.14285714285714285 1.0
351 11 0 0.8285714285714286 0.17142857142857143 1.0
352 11 0 0.8 0.2 1.0
353 11 0 0.7714285714285715 0.22857142857142856 1.0
354 11 0 0.7428571428571429 0.2571428571428571 1.0
355 11 0 0.7142857142857143 0.2857142857142857 1.0
356 11 0 0.6857142857142857 0.3142857142857143 1.0
357 11 0 0.6571428571428571 0.34285714285714286 1.0
358 11 0 0.6285714285714286 0.37142857142857144 1.0
359 11 0 0.6 0.4 1.0
360 11 0 0.5714285714285714 0.42857142857142855 1.0
361 11 0 0.5428571428571428 0.45714285714285713 1.0
362 11 0 0.5142857142857142 0.4857142857142857 1.0
363 0 11 0.5142857142857142 0.4857142857142857 1.0
364 0 11 0.5428571428571428 0.45714285714285713 1.0
365 0 11 0.5714285714285714 0.42857142857142855 1.0

**Comment by skymandr** [comment]
Så här ser det ut om man använder doys från https://github.com/Odin-SMR/qsmr-data/blob/master/DataPrecalced/SpeciesApriori/Bdx/apriori_O3.mat och låter input doy vara en `float` istället för en `int`:

`![doy](https://user-images.githubusercontent.com/358614/101654416-ce655f00-3a40-11eb-8f2e-8002fae3aff9.png)

**Comment by skymandr** [comment]
Work continues in #94
