### ISSUE TITLE
missing fonts

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin-api#55]
After a recent update, we have missing fonts warnings. See 
![odin_missingfonts](https://user-images.githubusercontent.com/358614/90023326-e7891980-dcb3-11ea-86a0-f4b2eacd8140.png)

**Comment by local-minimum** [comment]
It might just be that the requested weights no longer exists, if I remember correctly there was some change to which are standard. Or it might be because of license changes since the full font costs :dollar:

**Comment by skymandr** [comment]
> It might just be that the requested weights no longer exists, if I remember correctly there was some change to which are standard. Or it might be because of license changes since the full font costs dollar

But it says 404 for a local resource, so I think we are missing something. Perhaps they were removed when we migrated to npm?

**Comment by local-minimum** [comment]
Oh yes, they would not be in the same place I guess unless webpacked there. But I have a feeling something has changed with font awesome from how it used to work and how it is now too

**Comment by skymandr** [comment]
The fonts are installed, and we do use them, but there are two problems:
- the fonts are installed under `/static/js`, which is not where fonts should be,
- the code looks for them under `/`, which is neither were they are now where they should be.
