### ISSUE TITLE
linting not done

### ISSUE THREAD

**Issue by local-minimum** [Odin-SMR/odin-api#7]
- jenkins pipeline
- github action
- github plugin
- commit hook

❓

**Comment by skymandr** [comment]
Is linting done for Python?

**Comment by local-minimum** [comment]
Linting is done for python. It could be done for javascript with something like this as a script in `package.json`:

```
    "lint-changes": "git diff origin/master --name-only --relative --diff-filter=ACRMTU ${FILES:-./src} | grep -e '\\.jsx\\?$' | xargs --no-run-if-empty -t npx eslint --${FIX:-fix-dry-run}"  
```

But I think we would need to restructure all javascript code to use modern tools like webpack and proper use of npm.
