### ISSUE TITLE
Add an example on how to use the VDS on Data access page

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#74]
ESA requested an example on how to use the verification dataset to do comparisons with other mission (included in the VDS)

**Comment by skymandr** [comment]
There is an example in the VDS-document that we could copy, but just to be clear on this: We serve copies of other research groups' data sets through this API and have previously elected not to share the VDS API publicly, for fear of treading on a few toes. Are we ok to do this, @donal-mur ?
