### ISSUE TITLE
Add a link to the MesosphEO dataset

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#76]
@donal-mur : Should it be a news item as with the SANOMA model with links to an article and some additional text or just a menu item in "databrowser" menu?

ask Kristel?

**Comment by skymandr** [comment]
Or both..?

**Comment by donal-mur** [comment]
yes ask Kristell.  I thinks both are good

**Comment by skymandr** [comment]
Here are a few links to the project, for reference: http://mesospheo.fmi.fi/ https://research.chalmers.se/project/6720
