### ISSUE TITLE
Version 3 release text

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#77]
@donal-mur write a short "release note" for the wen site.

**Comment by donal-mur** [comment]
We are happy to announce the release of version 3 of the Odin dataset. This work has been supported by ESA and has involved the following:

- A complete reprocessing of the level 0 data to level 1. This included an improved algorithm for selection of background spectra for calibration, a time and temperature dependent frequency correction and automated removal of baseline.

- An upgraded level 2 processing scheme where mesospheric and stratospheric products were treated separately with optimised retrieval settings and where necessary improved spectroscopic parameters.

- A comprehensive validation exercise against other instruments.

Some highlights include :

- Recovery of the mesospheric CO dataset for the entire mission where a failed Phase locked loop had caused the frequency to drift and processing failure
- A greatly improved ozone dataset
- Bet

ter consistency between the two mesospheric water vapour products

**Comment by skymandr** [comment]
Ska jag ta bort nyheten från mars när jag lägger till denna, eller ska den vara kvar? @joakimmoller @donal-mur
