### ISSUE TITLE
Se till att netCDF filerna hålls uppdaterade

### ISSUE THREAD

**Issue by donal-mur** [Odin-SMR/odin-api#87]
Senast netCDF filer är 2019-12. Hur kan vi håller dessa någorlunda uppdaterade?

**Comment by BengtRydberg** [comment]
på denna url finns en kofiguration som säger vilka produkter vi försöker hålla uppdaterade:

http://odin.rss.chalmers.se/level2_download/config/odinl2.json

filen odin2.json definierar vilka produkter som vi generar månatliga nc-filer för
fram till 3 mån from nu. om en gammal fil redan finns skrivs den inte över.
det här ska skötas via ett crontab job som körs en gång i månaden.

lägger man till en produkt i odinl2.json så genereras måndsfiler för hela missionen
för denna produkt. 

Det finns möjlighet att manuellt gå in och skriva över gamla månadsfiler om man vill.
