### ISSUE TITLE
Notebooks should be python 3

### ISSUE THREAD

**Issue by local-minimum** [Odin-SMR/odin-api#9]
![Screenshot from 2020-04-02 10-54-28](https://user-images.githubusercontent.com/8041100/78229691-a0eb0d80-74d0-11ea-9e1f-5f79d81c4f28.png)

Also this indicates that they haven't been run in a very long time so one should also very that it all works and are correct, or they ought to be removed.

**Comment by joakimmoller** [comment]
remove!
