### ISSUE TITLE
Fix VMR interpolation

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin-api#94]
The problem with the apriori has been identified to be due to a faulty day of year interpolation in `get_vmr_interpolated_for_doy` in `read_apriori.py`. See #43 for details. This needs to be fixed and results recalculated.

# DoD:
- [ ] Fix the interpolation
- [ ] Regression tests

Make new tasks for:
- [ ] Re-run L2 processing for the affected period (mainly January and December each year, though there are minor errors around each apriori date as well, again see #43) for all species.
- [ ] Regenerate netcdf files (maybe this is done automatically?)

Check with @donal regarding these and create tasks if necessary:
- [ ] MesoSpheo netcdfs?
- [ ] Update PVER analysis..?

**Comment by donal-mur** [comment]
Is #43 now closed?

We can probably get away with only doing fm02 -  mid dec to mid jan
the NetCDF do not have the bad profiles (filtered by quality criteria så not urgent but the API delivers the bad one.

Need to check the other products -  strange that I only saw it in FM02 - I see big apriois in fm01 but the inversion seems to ignore them .  If we are luckly the others will too

**Comment by skymandr** [comment]
> We can probably get away with only doing fm02 - mid dec to mid jan

The simulations of weights in #43 indicate that the problem exists approximately 25 days on either side of new year.

> Need to check the other products - strange that I only saw it in FM02 - I see big apriois in fm01 but the inversion seems to ignore them . If we are luckly the others will too

I don't know how much extra time it would take to rerun all, but it would probably salvage a lot of data that has hitherto been discarded.
