### ISSUE TITLE
Update ECMWF key

### ISSUE THREAD

**Issue by skymandr** [Odin-SMR/odin-api#99]
We may have a new one that we should use.

Probably home directory on malachite

**Comment by BengtRydberg** [comment]
det ser inte ut som vi använder den här nyckeln längre (för https://apps.ecmwf.int/v1). Iallafall inte i odinapi. 
där laddar vi ned data genom cds api (https://cds.climate.copernicus.eu/api/v2): 
som använder en annan nyckelfil. 
Har hur som hellst uppdaterat ecmwf nyckelfilen på malachite.

**Comment by skymandr** [comment]
Menar du att du uppdaterat nyckeln vi använder eller den vi inte använder?

**Comment by BengtRydberg** [comment]
jag har uppdaterat nyckeln som donal skickat till oss. den används inte av odinapi. så det som odinapi använder är orört.
